language: python
python: "3.6"
before_install:
- wget https://github.com/jgm/pandoc/releases/download/2.2.1/pandoc-2.2.1-1-amd64.deb &&
  sudo dpkg -i pandoc-2.2.1-1-amd64.deb
- wget https://github.com/lierdakil/pandoc-crossref/releases/download/v0.3.2.0/linux-ghc84-pandoc22.tar.gz &&
  tar -xvzf linux-ghc84-pandoc22.tar.gz && sudo chmod +x pandoc-crossref && sudo mv pandoc-crossref /usr/local/bin
install: pip install pandocfilters
before_script:
- python --version
- pandoc --version
- pandoc-citeproc --version
- pandoc-crossref --version
- latexmk -version
- pdflatex -version
- biber -version
before_deploy:
- git config --local user.name "Florian Beetz"
- git config --local user.email "florian1.beetz@stud.uni-bamberg.de"
- git tag "v-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
script:
- make
deploy:
  provider: releases
  api_key:
    secure: dUoe7TM/UdeH0g1R2o3C25/CY2nLYhD784bjM9NhiZmVi0xDnskPNDo7y2lguRFm68hM9vM1wuPh/+SDVMqT1h4bnCnlb5adxUBbrmZ0ZwzjefT8wzSXyJBFqtN2wrPxnobBO4aCOLOsIMDjuKKvY37025/l36WQqisNORwD/Oeu5kZLT3EZJ9PWrV+vTiTA1mAgr5AlE8zpZVOMdchOk1vlHiZT4tN+78GvgaQtS3eGT7fPq02Yv9cG96+VxFoVu3uWYUGcWeH34xs0lAJuhJl0GxJmEUpvIOJHnIXTSevD2Z0zOgV6TLCds/PSYNYGYmhp1edlq5cOzhVUFNvtniYzBGPToWXvS3eB9MHvMilCS5nzAd6Iyhv8Gz46d74OvIj181ybwteI+doupglEqMOP8ylG8BISCJP4WfJ5eEkevHido8nfpOBm3JCnQJPQ42LkCn8rEqp6tCLsNOexT+qVkI/6BY/fNOsvuZgLKPyOZ3im6odMioRHb2uddcURf/ivKEKlT8qpN1x7w4A/ePTTCGMzcqhMv3htdeT0Ttv5anPvMb94fKW1cCwcTXRl5RMaX9Ui5DJSAHX8x6Tr9tiC1hAwjpg226Oc5mBz1ah0HR+DbvE+5dj0lHqQw88cYq1TBdqgo9S0mqIQV3upFOrvVd5xws2swr9yTBqbO9I=
  file: 
    - thesis.pdf
  skip_cleanup: true

notifications:
  email:
    on_success: never
    on_failure: always

addons:
  apt:
    packages:
      #- python3
      - inkscape
      - texlive-fonts-extra
      - texlive-fonts-recommended
      - texlive-latex-extra
      - texlive-latex-recommended
      - texlive-bibtex-extra
      - lmodern
      - latexmk
      - latex-xcolor
      - dvipng
      - biber